# Generated by Django 4.1.7 on 2023-03-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_message', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
